name: Apply Terraform Changes for Domain Security Auth

on:
  push:
    branches:
      - dev
      - qa
      - main
    paths:
      - 'trigger-*.log' 

jobs:
  terraform-apply:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
    defaults:
      run:
        shell: bash
    outputs:
      need_refresh: ${{ steps.set-flag.outputs.need_refresh }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5

      - name: Set Git config for commits (optional)
        run: |
          git config --global user.email "irispicis1962@gmail.com"
          git config --global user.name "Iris1902"

      - name: Initialize Terraform
        run: terraform init -migrate-state

      - name: Validate Terraform
        run: terraform validate

      - name: Format Terraform
        run: terraform fmt -recursive

      - name: Plan Terraform
        run: |
          terraform plan \
            -var="AWS_REGION=${{ secrets.AWS_REGION }}" \
            -var="AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" \
            -var="AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" \
            -var="AWS_SESSION_TOKEN=${{ secrets.AWS_SESSION_TOKEN }}" \
            -var="BRANCH_NAME=${{ github.ref_name }}"
      
      - name: Apply Terraform (con control de error)
        id: apply-tf
        run: |
          set +e
          terraform apply -auto-approve \
            -var="AWS_REGION=${{ secrets.AWS_REGION }}" \
            -var="AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" \
            -var="AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" \
            -var="AWS_SESSION_TOKEN=${{ secrets.AWS_SESSION_TOKEN }}" \
            -var="BRANCH_NAME=${{ github.ref_name }}"
          echo $? > tf_exit_code.txt
      - name: Set refresh flag if needed
        id: set-flag
        run: |
          code=$(cat tf_exit_code.txt)
          if [ "$code" != "0" ]; then
            echo "need_refresh=true" >> $GITHUB_OUTPUT
          else
            echo "need_refresh=false" >> $GITHUB_OUTPUT
          fi

  refresh-asg:
    runs-on: ubuntu-latest
    needs: terraform-apply
    if: needs.terraform-apply.outputs.need_refresh == 'true'
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Refrescar instancias de todos los ASG (uno a uno)
        run: |
          echo "🔄 Refrescando instancias de los Auto Scaling Groups de todos los microservicios, una por una..."
          for ASG_NAME in $(aws autoscaling describe-auto-scaling-groups --region $AWS_REGION --query "AutoScalingGroups[].AutoScalingGroupName" --output text); do
            echo "Procesando ASG: $ASG_NAME"
            INSTANCE_IDS=$(aws autoscaling describe-auto-scaling-groups \
              --region $AWS_REGION \
              --auto-scaling-group-names $ASG_NAME \
              --query "AutoScalingGroups[0].Instances[].InstanceId" \
              --output text)
            for id in $INSTANCE_IDS; do
              echo "Etiquetando y terminando instancia $id ..."
              aws ec2 create-tags --region $AWS_REGION --resources $id --tags Key=Name,Value=$ASG_NAME-instance
              aws autoscaling terminate-instance-in-auto-scaling-group --region $AWS_REGION --instance-id $id --no-should-decrement-desired-capacity
              echo "Esperando a que una nueva instancia esté InService..."
              while true; do
                NEW_INSTANCE_IDS=$(aws autoscaling describe-auto-scaling-groups \
                  --region $AWS_REGION \
                  --auto-scaling-group-names $ASG_NAME \
                  --query "AutoScalingGroups[0].Instances[?LifecycleState=='InService'].InstanceId" \
                  --output text)
                COUNT=$(echo $NEW_INSTANCE_IDS | wc -w)
                if [ "$COUNT" -ge 2 ]; then
                  echo "Nueva instancia en servicio. Continuando..."
                  break
                fi
                echo "Esperando 15 segundos..."
                sleep 15
              done
            done
          done
      - name: Forzar éxito si el refresco fue exitoso
        run: exit 0
